import type { GlossaryEntry } from '../../engine/types'

/**
 * FF14 术语词典。释义按社区通用理解整理，非官方文本。
 *
 * 约束：信件文本中凡以 `terms` 标注的黑话，必须在此存在条目（校验器 1g）。
 *
 * `linkedCharacterIds` 是**编辑注记**，由脚本从角色的 `statement.terms` 派生而来，
 * 不是手写的。界面上「常用此术语的角色」用的是运行时派生的
 * `content/index.ts → charactersUsingTerm()`，因此这个字段即使过期也不会显示错。
 *
 * 曾经有一条校验器要求「被正文使用的术语必须声明使用角色」，已废弃——
 * 那会让词典反过来决定角色能说什么：只要某个词条的注记是空的，
 * 任何角色都不能再用这个词。结果是梗类术语全书无人敢用，
 * 而它们恰恰是 PRD 最看重的社区语言。
 */
export const glossary: GlossaryEntry[] = [
  // ==========================================================================
  // 高难副本术语
  // ==========================================================================
  {
    id: 'jueben',
    term: '绝本',
    pinyin: 'jue ben',
    category: 'raid',
    brief: '最高难度的副本，比零式更难。',
    detail:
      '指「绝」系列高难度副本，是游戏内 PVE 内容的最高峰。要求极高的执行力与配合度，通常需要固定队长期开荒。',
    example: '绝本是什么？豆芽能进吗？',
    linkedCharacterIds: ['xiaoxing', 'yuanshan'],
    relatedTermIds: ['lingshi', 'kaifang'],
  },
  {
    id: 'lingshi',
    term: '零式',
    pinyin: 'ling shi',
    category: 'raid',
    brief: '高难度 raid 的「零式」难度版本。',
    detail:
      '同一副本的普通难度之上的挑战版本，掉落的装备更好。是大部分固定队每个版本的核心目标。',
    example: '炒不到80+就别来零式了。',
    linkedCharacterIds: ['chenxi', 'liefeng', 'xiaoxing', 'yuanshan'],
    relatedTermIds: ['jueben', 'chaogu', 'dujie'],
  },
  {
    id: 'kaifang',
    term: '开荒',
    pinyin: 'kai huang',
    category: 'raid',
    brief: '首次挑战副本，尚未通关的阶段。',
    detail: '指没有任何攻略经验、靠自己摸索机制的阶段。开荒期最容易产生摩擦。',
    example: '这周还在开荒P3，进度有点慢。',
    linkedCharacterIds: ['yuanshan'],
    relatedTermIds: ['dujie', 'menhu'],
  },
  {
    id: 'kuangbao',
    term: '狂暴',
    pinyin: 'kuang bao',
    category: 'raid',
    brief: '副本时间耗尽导致团灭。',
    detail:
      'BOSS 在限定时间内未被击败会释放全屏秒杀技能，称为狂暴。通常意味着团队输出不足。',
    example: '狂暴就狂暴了，再开一把。',
    linkedCharacterIds: ['liefeng', 'xiaoxing'],
    relatedTermIds: ['dujie', 'chaogu'],
  },
  {
    id: 'dujie',
    term: '渡劫',
    pinyin: 'du jie',
    category: 'raid',
    brief: '即将通关但未能成功，卡在最后一个阶段。',
    detail:
      '指已经打到副本的最后阶段，却因输出不足或机制失误团灭，距离通关「只差一步」。是最消耗心态的阶段。',
    example: '今晚渡劫，来熟练工，宝宝别来。',
    linkedCharacterIds: ['liefeng', 'xiaoxing'],
    relatedTermIds: ['kuangbao', 'menhu', 'benti'],
  },
  {
    id: 'menhu',
    term: '门神',
    pinyin: 'men shen',
    category: 'raid',
    brief: '副本中位于本体之前的 BOSS 战。',
    detail: '挡在最终 BOSS 之前的守关 BOSS，通常是检验团队是否够格的关卡。',
    example: 'P3门神渡劫，本体无进度。',
    linkedCharacterIds: [],
    relatedTermIds: ['benti', 'dujie'],
  },
  {
    id: 'benti',
    term: '本体',
    pinyin: 'ben ti',
    category: 'raid',
    brief: '副本的最终 BOSS 阶段。',
    detail: '打完门神之后进入的最终阶段，是整场战斗的高潮。',
    example: '门神终于过了，本体还得多练。',
    linkedCharacterIds: [],
    relatedTermIds: ['menhu'],
  },
  {
    id: 'chaogu',
    term: '炒股',
    pinyin: 'chao gu',
    category: 'raid',
    brief: '追求极限输出数据。',
    detail:
      '指为了把伤害数字打高而调整打法，有时会牺牲团队利益。贬义用法指只顾自己数据好看。',
    example: '这把我炒股了，输出没打满。',
    linkedCharacterIds: ['liefeng'],
    relatedTermIds: ['logs', 'lingshi'],
  },
  {
    id: 'famu',
    term: '伐木',
    pinyin: 'fa mu',
    category: 'raid',
    brief: '已经熟练通关后反复刷本。',
    detail: '副本不需要开荒了，只是重复通关拿装备，像砍树一样机械。',
    example: '今晚伐木，来熟练工。',
    linkedCharacterIds: ['yuanshan'],
    relatedTermIds: ['dibao'],
  },
  {
    id: 'dibao',
    term: '低保',
    pinyin: 'di bao',
    category: 'raid',
    brief: '通关必定掉落的兑换物品。',
    detail: '即使运气不好没掉装备，通关也会给一个保底道具，可以攒起来换装备。',
    example: '低保是什么？能吃吗？',
    linkedCharacterIds: ['tiebi', 'xiaoxing', 'yuanshan'],
    relatedTermIds: ['famu'],
  },
  {
    id: 'shouzhou',
    term: '首周',
    pinyin: 'shou zhou',
    category: 'raid',
    brief: '新版本开放后的第一周。',
    detail: '首周通关是硬核玩家的荣誉象征，也是压力最大的一周——很多矛盾都从这周开始。',
    example: '首周过不了没关系，别把亲友打散了。',
    linkedCharacterIds: ['chenxi', 'yuanshan'],
    relatedTermIds: ['kaifang', 'jueben'],
  },
  {
    id: 'logs',
    term: 'logs',
    pinyin: 'logs',
    category: 'raid',
    brief: '战斗记录网站上的输出评分。',
    detail: '第三方网站上传战斗日志后给出的伤害排名与颜色评分，社区常拿它衡量玩家水平。',
    example: '你这个logs比我当年好看多了。',
    linkedCharacterIds: ['liefeng', 'yuanshan'],
    relatedTermIds: ['chaogu'],
  },

  // ==========================================================================
  // 战斗机制术语
  // ==========================================================================
  {
    id: 'gangtie',
    term: '钢铁',
    pinyin: 'gang tie',
    category: 'mechanic',
    brief: 'BOSS 近身范围 AOE，需要远离。',
    detail: '以 BOSS 为中心的圆形攻击范围，站得太近会被打到，必须向外跑。',
    example: '钢铁月环我来吃，你们放心输出。',
    linkedCharacterIds: ['chenxi'],
    relatedTermIds: ['yuehuan', 'aoe'],
  },
  {
    id: 'yuehuan',
    term: '月环',
    pinyin: 'yue huan',
    category: 'mechanic',
    brief: '环形范围 AOE，需要贴近 BOSS。',
    detail: '与钢铁相反：BOSS 脚下是安全的，外圈一圈才是伤害区。钢铁与月环常常交替出现，最考验反应。',
    example: '钢铁月环我来吃，你们放心输出。',
    linkedCharacterIds: ['chenxi'],
    relatedTermIds: ['gangtie', 'aoe'],
  },
  {
    id: 'sixing',
    term: '死刑',
    pinyin: 'si xing',
    category: 'mechanic',
    brief: '对坦克造成极大伤害的技能，需要开减伤。',
    detail: 'BOSS 针对坦克释放的高伤害单体技能。不加减伤几乎必死，通常坦克之间会轮流承担。',
    example: '死刑来了，我开减伤。',
    linkedCharacterIds: [],
    relatedTermIds: ['mt'],
  },
  {
    id: 'fentan',
    term: '分摊',
    transparent: true,
    pinyin: 'fen tan',
    category: 'mechanic',
    brief: '被点名的玩家集合分担伤害。',
    detail: '伤害由站在一起的玩家共同承担，人越多每人受到的越少。散开反而会死。',
    example: '分摊站位，别散开。',
    linkedCharacterIds: [],
    relatedTermIds: ['aoe'],
  },
  {
    id: 'aoe',
    term: 'AOE',
    pinyin: 'a o e',
    category: 'mechanic',
    brief: '范围伤害技能。',
    detail: 'Area of Effect，指波及一片区域的伤害，需要靠走位规避。',
    example: '这波AOE有点密。',
    linkedCharacterIds: [],
    relatedTermIds: ['gangtie', 'yuehuan'],
  },
  {
    id: 'lb',
    term: 'LB',
    pinyin: 'lb',
    category: 'mechanic',
    brief: '极限技，全队共享的必杀技。',
    detail: 'Limit Break，队伍共同积攒的能量条。输出职业的 LB 用来打伤害，治疗的 LB 用来群体复活。',
    example: '赤魔一个人拉了六个，比奶妈LB还快。',
    linkedCharacterIds: [],
    relatedTermIds: ['fuhuo'],
  },

  // ==========================================================================
  // 职业与角色术语
  // ==========================================================================
  {
    id: 'mt',
    term: 'MT',
    pinyin: 'mt',
    category: 'job',
    brief: '主坦克，负责拉住 BOSS 仇恨。',
    detail: 'Main Tank。队伍里站在最前面、承担 BOSS 主要攻击的人，压力与责任都最大。',
    example: '我能当MT吗？我怕仇恨拉不稳。',
    linkedCharacterIds: ['chenxi'],
    relatedTermIds: ['sixing', 'guizu-lan'],
  },
  {
    id: 'h1',
    term: 'H1',
    pinyin: 'h1',
    category: 'job',
    brief: '主治疗，通常负责看住坦克。',
    detail: '队伍中的第一治疗位。很多团队默认 H1 要承担更多、更累的活，这常常是矛盾的来源。',
    example: '我也有奶不动的时候，别什么都指望H1。',
    linkedCharacterIds: ['yuejian'],
    relatedTermIds: ['liulan', 'fuhuo'],
  },
  {
    id: 'guizu-lan',
    term: '高贵蓝',
    pinyin: 'gao gui lan',
    category: 'job',
    brief: '坦克职业的戏称。',
    detail: '因坦克职业的图标与技能特效多为蓝色，社区戏称其为「高贵蓝」，也暗含坦克在队伍中的特殊地位。',
    example: '高贵蓝今天又不肯开减伤。',
    linkedCharacterIds: [],
    relatedTermIds: ['mt'],
  },
  {
    id: 'tangshi-long',
    term: '躺尸龙',
    pinyin: 'tang shi long',
    category: 'job',
    brief: '龙骑士因跳跃技能僵直大而频繁倒地。',
    detail: '龙骑士的部分技能在空中无法移动，容易被机制打死，因此被戏称为「躺尸龙」。',
    example: '豆芽慢慢来，我当初也是躺尸过来的。',
    linkedCharacterIds: ['chenxi'],
    relatedTermIds: ['longqi-houtiao'],
  },
  {
    id: 'longqi-houtiao',
    term: '龙骑后跳',
    pinyin: 'long qi hou tiao',
    category: 'job',
    brief: '龙骑士的回避跳跃使用不当会坠崖，经典名场面。',
    detail:
      '龙骑士有一个向后位移的技能，在没有护栏的地形上使用会直接掉下悬崖。已经成为一个经久不衰的社区梗。',
    example: '烈风一个后跳直接坠崖，99999刷了满屏。',
    linkedCharacterIds: [],
    relatedTermIds: ['tangshi-long'],
    memeRef: '龙骑后跳坠崖',
  },
  {
    id: 'heimo-wen',
    term: '黑魔纹',
    pinyin: 'hei mo wen',
    category: 'job',
    brief: '黑魔法师的魔法阵，不会随移动而移动。',
    detail:
      '站在阵内可以大幅提升输出，但阵不会跟着人走。因此黑魔常常宁可硬吃技能也不肯离开阵——社区名场面。',
    example: '黑魔被营救拉出来，立刻魔纹布回去，硬吃AOE。',
    linkedCharacterIds: [],
    relatedTermIds: ['aoe'],
    memeRef: '死也不出黑魔纹',
  },
  {
    id: 'chimo-laren',
    term: '赤魔拉人',
    pinyin: 'chi mo la ren',
    category: 'job',
    brief: '赤魔法师频繁复活队友，被称为「赤天开门」。',
    detail: '赤魔法师拥有快速复活他人的能力，团灭时常常一个人把全队拉起来，社区戏称「赤天开门」。',
    example: '赤魔一个人拉了六个，比奶妈LB还快。',
    linkedCharacterIds: [],
    relatedTermIds: ['lb', 'fuhuo'],
    memeRef: '赤天开门',
  },
  {
    id: 'tianci-chaohuo',
    term: '天赐超火',
    pinyin: 'tian ci chao huo',
    category: 'job',
    brief: '治疗给正在无敌的坦克使用天赐祝福，经典配合失误。',
    detail:
      '坦克的无敌技能期间不会受到伤害，此时治疗使用「天赐祝福」（把血量补满的大招）会完全浪费。是治疗与坦克之间最经典的沟通事故。',
    example: '月见天赐了正在超火流星的无敌T，语音里沉默了。',
    linkedCharacterIds: [],
    relatedTermIds: ['h1'],
    memeRef: '天赐超火',
  },
  {
    id: 'lalafei-shicai',
    term: '拉拉肥/食材',
    pinyin: 'la la fei shi cai',
    category: 'job',
    brief: '拉拉菲尔族，因游戏内道具说明而被称为「食材」。',
    detail:
      '游戏中的拉拉菲尔族体型娇小，加上某些道具的说明文字，社区逐渐形成了「拉拉肥是食材」的玩笑。属于流传最广的社区梗之一。',
    example: '你再OT我就把你当食材炖了。',
    linkedCharacterIds: [],
    relatedTermIds: [],
    memeRef: '拉拉肥食材',
  },

  // ==========================================================================
  // 社交系统术语
  // ==========================================================================
  {
    id: 'douya',
    term: '豆芽',
    pinyin: 'dou ya',
    category: 'social',
    brief: '新玩家的标识。',
    detail:
      '游戏内对新人的称呼，头顶会有一个豆芽图标。豆芽期是每个老玩家都经历过的阶段，也因此成为「善意传递」的象征。',
    example: '豆芽慢慢来，我当初也是被人拖过本的。',
    linkedCharacterIds: ['chenxi', 'tiebi', 'xiaoxing', 'yuanshan'],
    relatedTermIds: ['daoshi'],
  },
  {
    id: 'daoshi',
    term: '导师',
    transparent: true,
    pinyin: 'dao shi',
    category: 'social',
    brief: '获得指导者资格的玩家，分会带豆芽。',
    detail:
      '满足条件后可申请的资格，分为战斗、生产、双修等类型。成为导师意味着愿意对新人的问题负责。',
    example: '他挂上导师标之后就再没摘下来过。',
    linkedCharacterIds: ['xiaoxing', 'yuanshan'],
    relatedTermIds: ['douya', 'madao'],
  },
  {
    id: 'madao',
    term: '妈导',
    pinyin: 'ma dao',
    category: 'social',
    brief: '像妈妈一样呵护豆芽的导师。',
    detail: '形容照顾得无微不至的导师，褒义里带一点点无奈。',
    example: '你这个妈导，连豆芽的传送费都要报销。',
    linkedCharacterIds: [],
    relatedTermIds: ['daoshi', 'douya'],
  },
  {
    id: 'budui',
    term: '部队（FC）',
    pinyin: 'bu dui',
    category: 'social',
    brief: '游戏中的公会组织，Free Company。',
    detail:
      '玩家自发组成的团体，拥有共同的房屋与仓库。部队的存续往往靠一两个人在维持，这正是很多故事的起点。',
    example: '部队不是我一个人的，房子也是大家的。',
    linkedCharacterIds: ['tiebi', 'xiaoxing', 'yuanshan'],
    relatedTermIds: ['tongxunbei', 'gongyu'],
  },
  {
    id: 'tongxunbei',
    term: '通讯贝（LS）',
    pinyin: 'tong xun bei',
    category: 'social',
    brief: '游戏内的聊天群组，Linkshell。',
    detail:
      '玩家可以自建并邀请他人的聊天频道。一个活跃的通讯贝往往承载着一群人的全部社交生活。',
    example: '跨服通讯贝建好了，随时来聊天。',
    linkedCharacterIds: ['linglan', 'tiebi', 'xiaoxing'],
    relatedTermIds: ['cwls', 'budui'],
  },
  {
    id: 'cwls',
    term: '跨服通讯贝（CWLS）',
    pinyin: 'cwls',
    category: 'social',
    brief: '可以跨服务器聊天的通讯贝。',
    detail:
      'Cross-world Linkshell，突破了服务器限制。对于分居不同服务器的朋友来说，这是唯一的联系纽带。',
    example: '跨服通讯贝建好了，随时来聊天。',
    linkedCharacterIds: ['linglan', 'tiebi', 'xiaoxing', 'yeyu'],
    relatedTermIds: ['tongxunbei'],
  },
  {
    id: 'qinyou',
    term: '亲友',
    transparent: true,
    pinyin: 'qin you',
    category: 'social',
    brief: '固定一起玩的搭档或好友。',
    detail: '比普通队友更近一层的关系。在固定队语境里，「别把亲友打散了」是一句很重的话。',
    example: '首周过不了没关系，别把亲友打散了。',
    linkedCharacterIds: [],
    relatedTermIds: ['budui', 'gudingdui'],
  },
  {
    id: 'gudingdui',
    term: '固定队',
    transparent: true,
    pinyin: 'gu ding dui',
    category: 'social',
    brief: '长期固定一起打高难的队伍。',
    detail:
      '成员相对稳定的小队。固定队的关系完全靠玩家之间的默契与道德维系，没有制度约束，因此格外脆弱也格外珍贵。',
    example: '我们固定队成立后的第一个高难周。',
    linkedCharacterIds: ['xiaoxing'],
    relatedTermIds: ['qinyou', 'kaifang'],
  },
  {
    id: 'fuqiang',
    term: '放浪神',
    pinyin: 'fang lang shen',
    category: 'social',
    brief: '跨服传送中的玩家，ID 后缀显示「放浪神加护」。',
    detail: '玩家跨服务器游玩时，名字后会带上的标记。带着一点漂泊的意味。',
    example: '看他挂着放浪神加护，就知道是别服来的。',
    linkedCharacterIds: ['tiebi', 'xiaoxing'],
    relatedTermIds: ['cwls'],
  },
  {
    id: 'guaji',
    term: '挂机',
    transparent: true,
    pinyin: 'gua ji',
    category: 'social',
    brief: '在线但不进行操作。',
    detail: '人还在游戏里，但什么都不做。对有些人来说，挂机是一种陪伴；对另一些人，是无法开口的疲惫。',
    example: '不用一直说话，挂机在一起也是一种陪伴。',
    linkedCharacterIds: ['linglan', 'yuejian'],
    relatedTermIds: ['tongxunbei'],
  },

  // ==========================================================================
  // 生产采集术语
  // ==========================================================================
  {
    id: 'hq',
    term: 'HQ/NQ',
    pinyin: 'hq nq',
    category: 'craft',
    brief: '高品质 / 普通品质的物品。',
    detail: 'High Quality 与 Normal Quality。制作时有一定概率产出 HQ，属性更好。',
    example: '这把能不能出HQ就看命了。',
    linkedCharacterIds: [],
    relatedTermIds: ['jinzhi'],
  },
  {
    id: 'jinzhi',
    term: '禁断',
    pinyin: 'jin zhi',
    category: 'craft',
    brief: '禁忌镶嵌，高级魔晶石镶嵌方式。',
    detail: '在装备已有的镶嵌孔之外强行打入魔石，有失败概率。是追求极限属性的手段。',
    example: '为了这身禁断，我把家底都掏空了。',
    linkedCharacterIds: [],
    relatedTermIds: ['hq'],
  },
  {
    id: 'yuwang',
    term: '鱼王/鱼皇',
    pinyin: 'yu wang',
    category: 'craft',
    brief: '钓鱼玩法中的稀有鱼类。',
    detail: '出现条件苛刻的稀有鱼，钓到需要运气与耐心。很多玩家把钓鱼当作离开团队纷争的避风港。',
    example: '今天又没钓到鱼王，明天再来。',
    linkedCharacterIds: ['yuanshan'],
    relatedTermIds: [],
  },

  // ==========================================================================
  // 房屋与幻化术语
  // ==========================================================================
  {
    id: 'huanhua',
    term: '幻化',
    transparent: true,
    pinyin: 'huan hua',
    category: 'housing',
    brief: '武具投影，改变装备外观的系统。',
    detail: '把喜欢的装备外观覆盖到当前装备上，纯粹为了好看。是很多人留在游戏里的理由之一。',
    example: '这套幻化我搭了一个晚上。',
    linkedCharacterIds: ['yeyu'],
    relatedTermIds: ['zhuangxiu'],
  },
  {
    id: 'zhuangxiu',
    term: '装修',
    transparent: true,
    pinyin: 'zhuang xiu',
    category: 'housing',
    brief: '房屋内部或外部的装潢。',
    detail: '用家具摆出各种造型，是房屋系统的核心玩法。一间屋子的样子往往能看出主人的状态。',
    example: '部队房重新装修了一遍，回来看看。',
    linkedCharacterIds: ['tiebi'],
    relatedTermIds: ['huanhua', 'gongyu'],
  },
  {
    id: 'gongyu',
    term: '公寓',
    transparent: true,
    pinyin: 'gong yu',
    category: 'housing',
    brief: '个人房间。',
    detail: '每个人都可以拥有的独立房间，是属于自己的那一小块地方。',
    example: '至少我的公寓还在。',
    linkedCharacterIds: ['yeyu', 'yuanshan'],
    relatedTermIds: ['zhuangxiu'],
  },

  // ==========================================================================
  // RP 与社区术语
  // ==========================================================================
  {
    id: 'rp',
    term: 'RP',
    pinyin: 'rp',
    category: 'rp',
    brief: 'Role Play，角色扮演。',
    detail: '玩家以自己构造的角色身份进行互动，而非以玩家身份。是艾欧泽亚里另一种生活的入口。',
    example: '我想开个RP号，扮演一个不存在的自己。',
    linkedCharacterIds: ['linglan', 'yeyu'],
    relatedTermIds: ['ic-ooc', 'rp-dian'],
  },
  {
    id: 'ic-ooc',
    term: '角色内/角色外（IC/OOC）',
    pinyin: 'ic ooc',
    category: 'rp',
    brief: '角色内 / 角色外，In Character / Out Of Character。',
    detail:
      'IC 指以角色身份说话，OOC 指跳出来以玩家身份说话。长时间分不清这两者，是很多 RP 玩家的困境。',
    example: 'RP标挂久了，分不清角色内和角色外了。',
    linkedCharacterIds: ['yeyu'],
    relatedTermIds: ['rp', 'rp-dian'],
  },
  {
    id: 'rp-dian',
    term: 'RP店',
    pinyin: 'rp dian',
    category: 'rp',
    brief: '角色扮演主题的玩家场所。',
    detail: '玩家经营的、以角色扮演为内容的场所，有店员、有剧情、有规矩。是 RP 玩家的主要活动空间。',
    example: 'RP店今晚开场，来坐坐。',
    linkedCharacterIds: ['linglan', 'yeyu'],
    relatedTermIds: ['rp', 'ic-ooc'],
  },
  {
    id: 'gpose',
    term: 'gpose',
    pinyin: 'gpose',
    category: 'rp',
    brief: '集体拍照模式。',
    detail: '游戏内的截图功能，可以摆姿势、打光、加滤镜。固定队的合影常常就是在这里拍的。',
    example: '来来来，gpose，我数三二一。',
    linkedCharacterIds: ['linglan'],
    relatedTermIds: ['nuannuan'],
  },
  {
    id: 'nuannuan',
    term: '暖暖',
    pinyin: 'nuan nuan',
    category: 'rp',
    brief: '以搭配外观为主要玩法的调侃。',
    detail: '把游戏玩成换装游戏，戏称为「艾欧泽亚暖暖」。不含贬义，更多是自嘲。',
    example: '本可以不打，衣服不能不换。',
    linkedCharacterIds: ['yeyu'],
    relatedTermIds: ['huanhua', 'gpose'],
  },

  // ==========================================================================
  // 游戏梗
  // ==========================================================================
  {
    id: 'cangqiong-baoan',
    term: '苍穹保安队',
    pinyin: 'cang qiong bao an dui',
    category: 'meme',
    brief: '玩家二创把大师兄形象与保安结合起来的梗。',
    detail: '由角色形象衍生出的社区二创梗，在社交场景中被广泛使用。',
    example: '你就是苍穹保安队队长吧。',
    linkedCharacterIds: [],
    relatedTermIds: [],
    memeRef: '苍穹保安队',
  },
  {
    id: 'tiandi-wanxiang',
    term: '天地万象皆随我意',
    pinyin: 'tian di wan xiang jie sui wo yi',
    category: 'meme',
    brief: '6.0 版本一段 BOSS 技能台词，因特效震撼成为梗。',
    detail: '因为演出效果极为震撼，成为玩家口口相传的名场面台词，常用于形容气势十足的时刻。',
    example: '他一句天地万象皆随我意，全场都安静了。',
    linkedCharacterIds: [],
    relatedTermIds: [],
    memeRef: '天地万象皆随我意',
  },
  {
    id: 'fuhuo',
    term: '复活',
    transparent: true,
    pinyin: 'fu huo',
    category: 'mechanic',
    brief: '把倒下的队友重新拉起来。',
    detail: '治疗与部分职业拥有复活技能。把复活名额全用在别人身上、自己倒下时没人管，是治疗玩家的经典困境。',
    example: '奶妈也要记得给自己留蓝，别把复活全交出去。',
    linkedCharacterIds: ['yuejian'],
    relatedTermIds: ['h1', 'lb'],
  },
  {
    id: 'liulan',
    term: '留蓝',
    pinyin: 'liu lan',
    category: 'mechanic',
    brief: '保留法力值以备不时之需。',
    detail: '治疗的法力是有限资源。把蓝全部用光会让团队在关键时刻没有续航——这既是操作问题，也是一种隐喻。',
    example: '奶妈也要记得给自己留蓝。',
    linkedCharacterIds: ['yuejian'],
    relatedTermIds: ['fuhuo', 'h1'],
  },
  {
    id: 'muzhuang',
    term: '木桩',
    pinyin: 'mu zhuang',
    category: 'job',
    brief: '训练场里用来练输出的假人。',
    detail: '不会反击的靶子，玩家在上面反复练习技能循环。在木桩前练三十遍，是一种很孤独的认真。',
    example: '这个循环我在木桩前练了三十遍。',
    linkedCharacterIds: ['liefeng'],
    relatedTermIds: ['logs', 'chaogu'],
  },

  // ==========================================================================
  // 扩充词条（源 txt §8.1 收录范围的补齐）
  // ==========================================================================

  // ---- 高难副本术语 ----
  {
    id: 'jishen',
    term: '极神',
    pinyin: 'ji shen',
    category: 'raid',
    brief: '蛮神讨灭战的强化版，俗称「极」。',
    detail:
      '同一场蛮神讨灭战的高难度版本，BOSS 的血量与机制都大幅加强，需要八人组队。极神是很多新人第一次接触「高难」的地方，也是不少固定队认识彼此的起点。',
    example: '第一次打极神，我连机制都没看清就躺了。',
    linkedCharacterIds: [],
    relatedTermIds: ['jueben', 'lingshi'],
  },
  {
    id: 'sansan',
    term: '33',
    pinyin: 'san san',
    category: 'raid',
    brief: '招募缩写：团灭三次就散队。',
    detail:
      '招募板上的常见约定——连灭三次就地解散，不多纠缠。写「33」的队伍通常是想高效过本、不愿反复陪练的人，因此也常常和「进度欺诈」一起出现在招募描述里。',
    example: '招募写了33，结果第三把还是没过，队直接就散了。',
    linkedCharacterIds: [],
    relatedTermIds: ['jindu-qizha', 'kaifang'],
  },
  {
    id: 'lingx-erx',
    term: '0x/2x',
    pinyin: 'ling x er x',
    category: 'raid',
    brief: '招募里的战利品箱子数量标识。',
    detail:
      '零式副本每周的宝箱数量取决于队伍中本周已通关的人数，通关的人越多箱子越少。于是招募时会直接写明「2x」（拿满两箱）或「0x」（不拿箱子，多为已通关者来陪练或练手），省去开打前的互相试探。',
    example: '这是0x队，我早就通了，就是来陪练的。',
    linkedCharacterIds: [],
    relatedTermIds: ['lingshi', 'famu', 'peilian'],
  },
  {
    id: 'jindu-qizha',
    term: '进度欺诈',
    transparent: true,
    pinyin: 'jin du qi zha',
    category: 'raid',
    brief: '谎报自己的副本进度，进队后被拆穿。',
    detail:
      '招募时声称自己已经打到哪里，实际毫无进度，一开口就露馅。对固定队来说这是比技术差更伤人的事——技术可以练，被消耗掉的是最基础的信任。',
    example: '他说自己过了P3，结果第一把就死在开场。',
    linkedCharacterIds: [],
    relatedTermIds: ['kaifang', 'dujie', 'sansan'],
  },
  {
    id: 'peilian',
    term: '陪练',
    transparent: true,
    pinyin: 'pei lian',
    category: 'raid',
    brief: '有偿陪别人练机制、过本的人。',
    detail:
      '由熟练玩家组成、按场次或时长收费陪打的队伍。对新手来说，陪练是花钱买时间；对老玩家来说，这是把手上的技术换成金币的方式。',
    example: '过不去就开个陪练队，别一群人硬耗着。',
    linkedCharacterIds: [],
    relatedTermIds: ['famu', 'dibao', 'lingx-erx'],
  },

  // ---- 战斗机制术语 ----
  {
    id: 'caita',
    term: '踩塔',
    pinyin: 'cai ta',
    category: 'mechanic',
    brief: '场上出现塔形区域，判定时需要站上去。',
    detail:
      'BOSS 会在场上留下若干塔形区域，结算时每座塔都要有人站上去，否则全队承受惩罚伤害。塔的分配通常在开打前就定好，谁漏了谁背锅——这也是固定队最常吵架的机制之一。',
    example: '踩塔的时候我跑错方向了，全队陪我吃了一次AOE。',
    linkedCharacterIds: [],
    relatedTermIds: ['fentan', 'aoe'],
  },
  {
    id: 'sankai',
    term: '散开',
    transparent: true,
    pinyin: 'san kai',
    category: 'mechanic',
    brief: '全员分散站位，避免伤害重叠。',
    detail:
      '与分摊相反的处理方式：被点名的玩家要彼此拉开距离，防止范围伤害叠在一起。该集合还是该散开，是每个高难玩家的第一课。',
    example: '这波是散开，别往我身上凑。',
    linkedCharacterIds: [],
    relatedTermIds: ['fentan', 'aoe'],
  },
  {
    id: 'laxian',
    term: '拉线',
    pinyin: 'la xian',
    category: 'mechanic',
    brief: '被连线的人需要拉开距离处理。',
    detail:
      'BOSS 与玩家之间、或玩家彼此之间会出现连线，被连到的人要往指定方向拉开，把线扯断或拉远。方向错了，线就会扫到别人——机制里最常见的连坐。',
    example: '我拉线往左边走，你别跟过来。',
    linkedCharacterIds: [],
    relatedTermIds: ['aoe', 'fentan'],
  },
  {
    id: 'zhengxie',
    term: '正点/斜点',
    pinyin: 'zheng dian xie dian',
    category: 'mechanic',
    brief: '场地标点：A~D 是正点，1~4 是斜点。',
    detail:
      '游戏内的标点系统里，A、B、C、D 落在四个正方向，1、2、3、4 落在四个对角方向，玩家因此分别叫它们「正点」和「斜点」。报位置、分配站位全靠它——「去斜点集合」比「往右后方跑」清楚得多。',
    example: '塔刷在斜点，我去1点，你去3点。',
    linkedCharacterIds: [],
    relatedTermIds: ['caita', 'aoe'],
  },
  {
    id: 'gcd',
    term: 'GCD',
    pinyin: 'gcd',
    category: 'mechanic',
    brief: '公共冷却时间，Global Cooldown。',
    detail:
      '所有技能共享的那条冷却，决定了输出的基本节奏。围着 GCD 排技能顺序、在不影响循环的位置插入能力技，是每个想打好输出的人都要下的功夫。',
    example: '你的GCD空转了，中间那下该插技能的。',
    linkedCharacterIds: [],
    relatedTermIds: ['dot', 'hot'],
  },
  {
    id: 'dot',
    term: 'DOT',
    pinyin: 'dot',
    category: 'mechanic',
    brief: '持续伤害，Damage over Time。',
    detail:
      '挂在敌人身上、随时间持续掉血的技能。开打前先把 DOT 铺满，是输出的基本礼仪——忘记补 DOT，队友一眼就能从伤害统计里看出来。',
    example: '我DOT掉了，先补一轮再开爆发。',
    linkedCharacterIds: [],
    relatedTermIds: ['hot', 'gcd'],
  },
  {
    id: 'hot',
    term: 'HOT',
    pinyin: 'hot',
    category: 'mechanic',
    brief: '持续治疗，Heal over Time。',
    detail:
      '在一段时间内持续回血的技能。治疗的日常就是在 HOT 与直接治疗之间取舍：铺得太早浪费，铺得太晚人已经没了。',
    example: 'T的血线很稳，HOT先铺上就够了。',
    linkedCharacterIds: [],
    relatedTermIds: ['dot', 'gcd'],
  },

  // ---- 职业与角色术语 ----
  {
    id: 'sandaoshi',
    term: '剑导/锤导/大皇冠',
    pinyin: 'jian dao chui dao da huang guan',
    category: 'job',
    brief: '指导者的三种类型：战斗、生产采集、双修。',
    detail:
      '战斗方向的指导者被叫做「剑导」，生产采集方向的叫「锤导」，两者资格兼备的则是「大皇冠」，头顶的图标会变成王冠。称号不同，愿意担下来的责任也不同。',
    example: '他是大皇冠，战斗和生产都带得动，豆芽问什么都能答上来。',
    linkedCharacterIds: [],
    relatedTermIds: ['daoshi', 'douya', 'madao'],
  },

  // ---- 社交系统术语 ----
  {
    id: 'cp',
    term: 'CP',
    pinyin: 'cp',
    category: 'social',
    brief: '陆行鸟搭档，也指游戏里的伴侣。',
    detail:
      '一层意思是陆行鸟棚里登记的那只搭档陆行鸟，另一层是玩家之间的伴侣关系（常与「烙印」连用）。两种用法都很常见，只能靠语境分辨。',
    example: '你们的CP是陆行鸟还是活人？',
    linkedCharacterIds: [],
    relatedTermIds: ['laoyin', 'shiershen'],
  },
  {
    id: 'xizaoshui',
    term: '洗澡水',
    pinyin: 'xi zao shui',
    category: 'social',
    brief: '幻想药的戏称，喝下去就能重新捏人。',
    detail:
      '使用后可以重新创建角色外观，从种族、性别到五官都能推翻重来。有人为了改一个鼻子喝下一瓶，也有人喝完才发现自己想念原来的那张脸。',
    example: '这瓶洗澡水我攒了半年，还没舍得喝。',
    linkedCharacterIds: [],
    relatedTermIds: ['huanhua', 'nuannuan'],
  },
  {
    id: 'laoyin',
    term: '烙印',
    pinyin: 'lao yin',
    category: 'social',
    brief: '游戏内的结婚，即「永结同心」。',
    detail:
      '玩家之间的誓约仪式，社区俗称「烙印」，仪式在格里达尼亚的十二神大圣堂举行。结束后两人会拿到誓约之戒与专属称号，也要给一整个通讯贝的人发请柬——于是婚礼常常变成一场社交考试。',
    example: '他们要烙印了，请柬发了一整个通讯贝。',
    linkedCharacterIds: [],
    relatedTermIds: ['cp', 'shiershen'],
  },

  // ---- 生产采集术语 ----
  {
    id: 'sanwei',
    term: '三围',
    pinyin: 'san wei',
    category: 'craft',
    brief: '生产的三项核心属性：作业精度、加工精度、制作力。',
    detail:
      '生产职业最重要的三项数值，社区戏称为「三围」。配装时把这三项堆够，才有资格谈手法——堆不够，再漂亮的循环也搓不出 HQ。',
    example: '他张口闭口就是三围，跟相亲似的。',
    linkedCharacterIds: [],
    relatedTermIds: ['hq', 'jitian'],
  },
  {
    id: 'jitian',
    term: '吉田概率学',
    pinyin: 'ji tian gai lv xue',
    category: 'craft',
    brief: '面板写着 98% 成功率却依然失败的自嘲。',
    detail:
      '制作时显示 98% 的 HQ 概率，结果还是出了 NQ——玩家把这种「概率学」算在制作人吉田直树头上，于是有了这个名字。后来也泛指游戏里一切「明明稳了却翻车」的瞬间。',
    example: '98%还能NQ，这就是吉田概率学。',
    linkedCharacterIds: [],
    relatedTermIds: ['hq', 'sanwei'],
  },
  {
    id: 'gongjiangge',
    term: '工匠歌',
    pinyin: 'gong jiang ge',
    category: 'craft',
    brief: '生产玩家形容「搓到麻木」的自嘲说法。',
    detail:
      '反复制作同一件东西时，玩家总会找点歌来熬过那段枯燥，久而久之「工匠歌」成了这种重复劳动的代名词。听的不是歌，是几百次同一条循环里的耐心。',
    example: '又搓了一晚上，工匠歌都听腻了。',
    linkedCharacterIds: [],
    relatedTermIds: ['sanwei', 'hq'],
  },
  {
    id: 'yugan',
    term: '轻杆/中杆/鱼王杆',
    pinyin: 'qing gan zhong gan yu wang gan',
    category: 'craft',
    brief: '钓鱼时咬钩力度的三档提示。',
    detail:
      '鱼咬钩时钓竿与浮标的反馈强弱不同，玩家据此判断上钩的是杂鱼还是大鱼：最轻的一档多半是小鱼，最强的一档俗称「鱼王杆」，往往意味着稀有鱼上钩了。老钓手只看那一下的弯度就知道该不该提竿。',
    example: '鱼王杆！快提竿！',
    linkedCharacterIds: [],
    relatedTermIds: ['yuwang'],
  },
  {
    id: 'fupoyi',
    term: '富婆衣',
    pinyin: 'fu po yi',
    category: 'craft',
    brief: '价格昂贵的时装。',
    detail:
      '指那些材料难得、市场上挂价惊人的外观装备。想要又买不起的时候，很多人会去自己学一门生产——然后发现成本更高。',
    example: '这件富婆衣我看了三个月，还是没买。',
    linkedCharacterIds: [],
    relatedTermIds: ['huanhua', 'nuannuan'],
  },
  {
    id: 'xiaofu',
    term: '校服',
    pinyin: 'xiao fu',
    category: 'craft',
    brief: '各职业专属的套装，俗称「校服」。',
    detail:
      '每个职业都有一套专属的装备外观（AF 装备），因为造型统一、一眼就能认出职业，被玩家称为「校服」。后来也泛指任何穿起来像制服的搭配。',
    example: '他衣柜里全是校服，一件别的都没有。',
    linkedCharacterIds: [],
    relatedTermIds: ['huanhua', 'nuannuan'],
  },

  // ---- 房屋与幻化术语 ----
  {
    id: 'yingsaifa',
    term: '硬塞法',
    pinyin: 'ying sai fa',
    category: 'housing',
    brief: '利用系统漏洞，把超量的家具塞进屋里。',
    detail:
      '房屋的家具摆放有数量上限，玩家摸索出各种操作技巧绕开限制，把多出来的家具硬塞进去。摆得下是本事，塞得进去是本事加运气。',
    example: '这屋子是用硬塞法做的，家具早就超标了。',
    linkedCharacterIds: [],
    relatedTermIds: ['zhuangxiu', 'fengmen'],
  },
  {
    id: 'fengmen',
    term: '封门',
    pinyin: 'feng men',
    category: 'housing',
    brief: '用家具把门口封住，让入口消失。',
    detail:
      '装修时用家具把房屋的门口挡住，从外面看根本找不到入口；也有人用它把不速之客挡在门外，或者把空间隔成隐藏的房间。家常的和诡异的，用的是同一个办法。',
    example: '他家的门被封住了，我在门口站了三分钟。',
    linkedCharacterIds: [],
    relatedTermIds: ['zhuangxiu', 'yingsaifa'],
  },
  {
    id: 'smlfang',
    term: 'S/M/L房',
    transparent: true,
    pinyin: 's m l fang',
    category: 'housing',
    brief: '房屋的三个大小等级。',
    detail:
      '游戏内的房屋按占地面积分为 S、M、L 三等，价格与内部空间依次递增。抢到 L 房是很多玩家的执念，而 S 房往往也够装下一个人全部的审美。',
    example: 'S房也能装得很好看，别小看它。',
    linkedCharacterIds: [],
    relatedTermIds: ['gongyu', 'zhuangxiu'],
  },
  {
    id: 'tingyuan',
    term: '庭院',
    transparent: true,
    pinyin: 'ting yuan',
    category: 'housing',
    brief: '房屋外面的院子，可以摆放庭具。',
    detail:
      '房屋自带的一小块室外空间，能摆树、栅栏、喷泉、小舞台。很多人把心思全花在院子里，因为那是唯一会被路过的人看见的部分。',
    example: '庭院里的花是我上周才种下的。',
    linkedCharacterIds: [],
    relatedTermIds: ['zhuangxiu', 'smlfang'],
  },

  // ---- RP 与社区术语 ----
  {
    id: 'qingrp',
    term: '轻RP/无RP',
    pinyin: 'qing rp wu rp',
    category: 'rp',
    brief: 'RP 的强度分类：轻松扮演与完全不扮演。',
    detail:
      '「轻RP」指以轻松的方式扮演角色、随时可以出戏聊游戏本身；「无RP」则是不扮演，直接以玩家身份说话。招募和 RP 店通常会把这两档标清楚，免得彼此误会。',
    example: '我们店是轻RP，不用一直端着角色说话。',
    linkedCharacterIds: [],
    relatedTermIds: ['rp', 'ic-ooc', 'rp-dian'],
  },
  {
    id: 'dapai',
    term: '打牌',
    transparent: true,
    pinyin: 'da pai',
    category: 'rp',
    brief: '玩九宫幻卡，游戏里的卡牌对战。',
    detail:
      '游戏内有一套收集与对战的卡牌玩法（九宫幻卡），可以和 NPC 或玩家对局、慢慢攒卡组。有人打本打到一半跑去打牌，也有人一整晚都泡在金碟打牌。',
    example: '不打了不打了，我去打牌了。',
    linkedCharacterIds: [],
    relatedTermIds: ['rp-dian', 'gpose'],
  },
  {
    id: 'shiershen',
    term: '十二神/结婚',
    pinyin: 'shi er shen jie hun',
    category: 'rp',
    brief: '十二神大圣堂，以及在那里举行的婚礼。',
    detail:
      '永结同心的仪式在十二神大圣堂举行，因此玩家说到「十二神」，指的往往就是结婚这件事。仪式分几个档次，请柬会发遍整个通讯贝——去不去、坐哪一桌，都是人情。',
    example: '他们约了下个月在十二神见面。',
    linkedCharacterIds: [],
    relatedTermIds: ['laoyin', 'cp'],
  },

  // ---- 游戏梗 ----
  {
    id: 'heifeiji',
    term: '黑肥鸡讨伐战',
    pinyin: 'hei fei ji tao fa zhan',
    category: 'meme',
    brief: 'KFC 联动套餐引发的社区梗。',
    detail:
      '与肯德基的联动期间，玩家为了拿到套餐附带的游戏内奖励纷纷去吃炸鸡、排队兑换，社区把这场集体行动戏称为「黑肥鸡讨伐战」。梗的核心从来不是鸡，是一群人为了同一个虚拟奖励同时变得很拼。',
    example: '为了黑肥鸡讨伐战，我一周吃了三次肯德基。',
    linkedCharacterIds: [],
    relatedTermIds: [],
    memeRef: '黑肥鸡讨伐战',
  },
  {
    id: 'houshi',
    term: '后室异空间',
    pinyin: 'hou shi yi kong jian',
    category: 'meme',
    brief: '玩家对「地图之外」那片空白空间的叫法。',
    detail:
      '卡位、bug 或某些特殊路线会把人送出发地图边界，到达一片只剩模型与贴图、没有 NPC 也没有音乐的空白区域。因为空旷、重复、安静得诡异，玩家把它叫作「后室」或「异空间」。',
    example: '我们卡bug跑到后室异空间去了，一个人都没有。',
    linkedCharacterIds: [],
    relatedTermIds: ['chort'],
    memeRef: '后室异空间',
  },
  {
    id: 'chort',
    term: '7.5版本Chort',
    pinyin: 'chort',
    category: 'meme',
    brief: '7.5 版本副本里的 BOSS，也成了玩家之间的口头梗。',
    detail:
      '7.5 版本 100 级副本 The Clyteum 中段的 BOSS，名字在斯拉夫语里意为「恶魔」。因为名字与造型都足够怪，上线后很快被玩家做成梗，用来形容版本初期那些离谱、说不清的场面。',
    example: '这周的本排得跟Chort一样，全员神志不清。',
    linkedCharacterIds: [],
    relatedTermIds: ['houshi'],
    memeRef: '7.5版本Chort',
  },
]
